### ISSUE TITLE
Meta 2020.1

### ISSUE THREAD

**Issue by gilvandovieira** [gilvandovieira/meta#1]
Below are some projects that I should develop:
- [ ] Restaurant app (React Native)
- [ ] Voice recorder app (Flutter app)
- [ ] Home dvd collection (Progressive web app)

**Comment by gilvandovieira** [comment]
https://github.com/gilvandovieira/desafio2

**Comment by gilvandovieira** [comment]
- [ ] https://github.com/gilvandovieira/challenge

**Comment by gilvandovieira** [comment]
- [ ] https://github.com/gilvandovieira/desafio-arquivo

**Comment by gilvandovieira** [comment]
- [ ] Home dvd collection 46402cec8da8ee19b30bef1c901ff88d207af94f #5

**Comment by gilvandovieira** [comment]
- [ ] https://github.com/gilvandovieira/app-ideas
